// export const DECREMENTCAKE="DECREMENTCAKE"
// export const INCREMENTCAKE="INCREMENTCAKE"
// export const DECREMENTICECREAM="DECREMENTICECREAM"
// export const INCREMENTICECREAM="INCREMENTICECREAM"

export const variable={
    DECREMENTCAKE:'DECREMENTCAKE',
    INCREMENTCAKE:'INCREMENTCAKE',
    DECREMENTICECREAM:'DECREMENTICECREAM',
    INCREMENTICECREAM: 'INCREMENTICECREAM'
}